server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adelifehub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: "replace-with-a-long-random-secret-string"
    expireSeconds: 3600
  upload:
    dir: uploads
